import Head from "next/head";
import Contact from "../components/contact";
import Footer from "../components/footer";
import Navbar from "../components/navbar";
import Newsletter from "../components/newsletter";
import Services from "../components/services";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ahng - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-hero">
          <Navbar />
          <Newsletter />
          <Services />
          <Contact />
          <Footer />
        </div>
      </main>
    </div>
  );
}
