import Head from "next/head";
import Navbar from "../components/navbar";
import Newsletter from "../components/newsletter";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ahng - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-hero">
          <div className="max-w-screen-xl mx-auto px-6">
            <Navbar />
            <Newsletter />
          </div>
        </div>
      </main>
    </div>
  );
}
