import Head from "next/head";
import Contact from "../components/contact";
import Footer from "../components/footer";
import Navbar from "../components/navbar";
import Newsletter from "../components/newsletter";
import Services from "../components/services";
import Slider from "../components/slider";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ahng - Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div className="bg-hero">
          <Navbar />
          <Slider />
          <Newsletter />
        </div>
        <Services />
        <Contact />
        <Footer />
      </main>
    </div>
  );
}
